In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### Sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Define the vocab size
voc_size = 10000

In [8]:
## One hot representation of every word
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

#-> this will give index of each word where it is present in 10000 voc

[[9283, 1747, 7598, 7733],
 [9283, 1747, 7598, 2232],
 [9283, 6928, 7598, 9987],
 [4574, 9755, 1372, 6103, 5139],
 [4574, 9755, 1372, 6103, 7151],
 [6866, 9283, 4737, 7598, 2116],
 [112, 532, 3842, 6103]]

In [17]:
## Word Embedding representation
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## We need to make all sent of same size -> we use pad_sequences and set max sent_len add 
## zeroes if sent length less than max-> it is called prepadding/postpadding (zeroes kha ayegi age ya picche)
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 9283 1747 7598 7733]
 [   0    0    0    0 9283 1747 7598 2232]
 [   0    0    0    0 9283 6928 7598 9987]
 [   0    0    0 4574 9755 1372 6103 5139]
 [   0    0    0 4574 9755 1372 6103 7151]
 [   0    0    0 6866 9283 4737 7598 2116]
 [   0    0    0    0  112  532 3842 6103]]


In [13]:
## Feature Representation
dim=10

In [19]:
model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(input_dim=voc_size,output_dim=dim)
])
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step


array([[[-7.19287246e-03,  4.21737693e-02, -1.48609653e-02,
         -4.82899658e-02,  4.41779941e-03, -1.72856562e-02,
          2.81632207e-02, -2.92109847e-02, -4.57468741e-02,
         -5.71433455e-03],
        [-7.19287246e-03,  4.21737693e-02, -1.48609653e-02,
         -4.82899658e-02,  4.41779941e-03, -1.72856562e-02,
          2.81632207e-02, -2.92109847e-02, -4.57468741e-02,
         -5.71433455e-03],
        [-7.19287246e-03,  4.21737693e-02, -1.48609653e-02,
         -4.82899658e-02,  4.41779941e-03, -1.72856562e-02,
          2.81632207e-02, -2.92109847e-02, -4.57468741e-02,
         -5.71433455e-03],
        [-7.19287246e-03,  4.21737693e-02, -1.48609653e-02,
         -4.82899658e-02,  4.41779941e-03, -1.72856562e-02,
          2.81632207e-02, -2.92109847e-02, -4.57468741e-02,
         -5.71433455e-03],
        [-4.99317534e-02, -1.70894377e-02, -2.05523614e-02,
         -1.83913708e-02, -4.85988148e-02,  6.02129847e-03,
         -1.08621605e-02,  2.36233212e-02,  4.079296

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 9283, 1747, 7598, 7733], dtype=int32)

In [24]:

model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[[-0.00719287,  0.04217377, -0.01486097, -0.04828997,
          0.0044178 , -0.01728566,  0.02816322, -0.02921098,
         -0.04574687, -0.00571433],
        [-0.00719287,  0.04217377, -0.01486097, -0.04828997,
          0.0044178 , -0.01728566,  0.02816322, -0.02921098,
         -0.04574687, -0.00571433],
        [-0.00719287,  0.04217377, -0.01486097, -0.04828997,
          0.0044178 , -0.01728566,  0.02816322, -0.02921098,
         -0.04574687, -0.00571433],
        [-0.00719287,  0.04217377, -0.01486097, -0.04828997,
          0.0044178 , -0.01728566,  0.02816322, -0.02921098,
         -0.04574687, -0.00571433],
        [-0.04993175, -0.01708944, -0.02055236, -0.01839137,
         -0.04859881,  0.0060213 , -0.01086216,  0.02362332,
          0.04079297,  0.04089028],
        [ 0.03469941, -0.04789215, -0.01843226,  0.01164143,
          0.01328247,  0.04539875, -0.04890221, -0.04994537,
         -0.00590112, -0.01280228],
        [ 0.02857028, -0.04672556, -0.03232193,  0.0